Repository jupyter-server/jupyter-resource-usage, pull requests merged in 2021-12, with the labels that each got.

#113 catch psutil exceptions
  jupyter_resource_usage/api.py
Labels: enhancement

#105 Add CPU display to extension
  jupyter_resource_usage/static/main.js
Labels: enhancement

#115 Adopt the Jupyter Releaser, update Jupyter Packaging
  .eslintignore
  .eslintrc.js
  .github/workflows/build.yml
  .github/workflows/check-release.yml
  .github/workflows/enforce-labels.yml
  .github/workflows/lint.yml
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  .prettierignore
  .prettierrc
  CHANGELOG.md
  CONTRIBUTING.md
  MANIFEST.in
  README.md
  RELEASE.md
  binder/environment.yml
  binder/postBuild
  jupyter-config/nbconfig/notebook.d/jupyter_resource_usage.json
  jupyter_resource_usage/__init__.py
  jupyter_resource_usage/_version.py
  jupyter_resource_usage/server_extension.py
  jupyter_resource_usage/tests/test_basic.py
  lerna.json
  package.json
  packages/labextension/.prettierignore
  packages/labextension/package.json
  packages/labextension/yarn.lock
  pyproject.toml
  setup.cfg
  setup.py
  yarn.lock
Labels: maintenance

#116 Automated Changelog Entry for 0.6.1 on master
  CHANGELOG.md
Labels: documentation

#117 Point the Binder link to the default branch
  README.md
Labels: documentation
