Repository jupyter-server/jupyter-resource-usage, pull requests merged in 2023-07, with the labels that each got.

#195 Update to Jupyterlab 4
  .github/workflows/build.yml
  .github/workflows/check-release.yml
  .github/workflows/lint.yml
  .github/workflows/tests.yml
  .gitignore
  .yarnrc.yml
  binder/environment.yml
  package.json
  packages/labextension/package.json
  pyproject.toml
  yarn.lock
Labels: maintenance

#201 Require Python 3.8+
  .github/workflows/tests.yml
  pyproject.toml
Labels: maintenance

#202 Integrate `jupyterlab-system-monitor` extension
  package.json
  packages/labextension/package.json
  packages/labextension/schema/topbar-item.json
  packages/labextension/src/cpuView.tsx
  packages/labextension/src/index.ts
  packages/labextension/src/indicator.tsx
  packages/labextension/src/memoryUsage.tsx
  packages/labextension/src/memoryView.tsx
  packages/labextension/src/model.ts
  packages/labextension/src/resourceUsage.tsx
  packages/labextension/style/base.css
  yarn.lock
Labels: enhancement

#205 Update README and fix settings file
  README.md
  doc/kernel-usage.png
  doc/settings.png
  doc/statusbar-cpu.png
  doc/statusbar-warn.png
  doc/statusbar.png
  doc/topbar.gif
  packages/labextension/schema/topbar-item.json
  screenshot.png
  warn-screenshot.png
Labels: documentation

#207 Make `IStatusBar` optional for `resourceStatusPlugin`
  packages/labextension/src/index.ts
Labels: maintenance

#206 Handle `currentWidget` in `KernelWidgetTracker`
  packages/labextension/src/index.ts
  packages/labextension/src/panel.ts
  packages/labextension/src/tracker.ts
  packages/labextension/src/widget.tsx
Labels: bug
